import type { ThemeTemplate, InvitationSection } from '../types';

const DEFAULT_SECTIONS: InvitationSection[] = [
  { id: 'cover', type: 'cover', enabled: true, sort_order: 0 },
  { id: 'islamic_greeting', type: 'islamic_greeting', enabled: true, sort_order: 1 },
  { id: 'invitation_text', type: 'invitation_text', enabled: true, sort_order: 2 },
  { id: 'couple', type: 'couple', enabled: true, sort_order: 3 },
  { id: 'event_details', type: 'event_details', enabled: true, sort_order: 4 },
  { id: 'countdown', type: 'countdown', enabled: true, sort_order: 5 },
  { id: 'itinerary', type: 'itinerary', enabled: true, sort_order: 6 },
  { id: 'location', type: 'location', enabled: true, sort_order: 7 },
  { id: 'contact', type: 'contact', enabled: true, sort_order: 8 },
  { id: 'rsvp', type: 'rsvp', enabled: true, sort_order: 9 },
  { id: 'money_gift', type: 'money_gift', enabled: true, sort_order: 10 },
  { id: 'gallery', type: 'gallery', enabled: true, sort_order: 11 },
  { id: 'guestbook', type: 'guestbook', enabled: true, sort_order: 12 },
  { id: 'calendar_save', type: 'calendar_save', enabled: true, sort_order: 13 },
  { id: 'footer', type: 'footer', enabled: true, sort_order: 14 },
];

export const THEME_TEMPLATES: ThemeTemplate[] = [
  {
    id: 'elegant-gold',
    name: 'Elegant Gold',
    name_ms: 'Emas Elegan',
    description: 'Timeless warm gold on cream — the classic luxury wedding card',
    preview_colors: ['#8B6F4E', '#D4AF37', '#FDF8F0', '#2C1810'],
    theme_config: {
      primary_color: '#8B6F4E',
      secondary_color: '#D4AF37',
      accent_color: '#F5E6D3',
      bg_color: '#FDF8F0',
      text_color: '#2C1810',
      font_display: 'Playfair Display',
      font_body: 'Poppins',
      font_arabic: 'Amiri',
      ornament_style: 'classic',
    },
    default_sections: DEFAULT_SECTIONS,
  },
  {
    id: 'sage-garden',
    name: 'Sage Garden',
    name_ms: 'Taman Sage',
    description: 'Soft sage green with botanical elegance — fresh and natural',
    preview_colors: ['#6B7F5E', '#A8B89A', '#F5F7F2', '#2D3A28'],
    theme_config: {
      primary_color: '#6B7F5E',
      secondary_color: '#A8B89A',
      accent_color: '#E8EDE4',
      bg_color: '#F5F7F2',
      text_color: '#2D3A28',
      font_display: 'Cormorant Garamond',
      font_body: 'Poppins',
      font_arabic: 'Amiri',
      ornament_style: 'floral',
    },
    default_sections: DEFAULT_SECTIONS,
  },
  {
    id: 'royal-navy',
    name: 'Royal Navy',
    name_ms: 'Biru Diraja',
    description: 'Deep navy blue with gold accents — regal and commanding',
    preview_colors: ['#1B2A4A', '#C9A96E', '#F0EDE6', '#0D1829'],
    theme_config: {
      primary_color: '#1B2A4A',
      secondary_color: '#C9A96E',
      accent_color: '#E8E2D6',
      bg_color: '#F0EDE6',
      text_color: '#0D1829',
      font_display: 'Playfair Display',
      font_body: 'Poppins',
      font_arabic: 'Amiri',
      ornament_style: 'classic',
    },
    default_sections: DEFAULT_SECTIONS,
  },
  {
    id: 'blush-rose',
    name: 'Blush Rose',
    name_ms: 'Mawar Merah Jambu',
    description: 'Soft pink and rose gold — romantic and feminine',
    preview_colors: ['#B76E79', '#D4A0A7', '#FFF5F5', '#4A2028'],
    theme_config: {
      primary_color: '#B76E79',
      secondary_color: '#D4A0A7',
      accent_color: '#F5E0E3',
      bg_color: '#FFF5F5',
      text_color: '#4A2028',
      font_display: 'Cormorant Garamond',
      font_body: 'Poppins',
      font_arabic: 'Amiri',
      ornament_style: 'floral',
    },
    default_sections: DEFAULT_SECTIONS,
  },
  {
    id: 'midnight-luxe',
    name: 'Midnight Luxe',
    name_ms: 'Kemewahan Malam',
    description: 'Dark moody background with gold — dramatic and modern',
    preview_colors: ['#D4AF37', '#C9A96E', '#1A1A2E', '#F0E6D3'],
    theme_config: {
      primary_color: '#C9A96E',
      secondary_color: '#D4AF37',
      accent_color: '#2A2A3E',
      bg_color: '#1A1A2E',
      text_color: '#F0E6D3',
      font_display: 'Playfair Display',
      font_body: 'Poppins',
      font_arabic: 'Amiri',
      ornament_style: 'geometric',
    },
    default_sections: DEFAULT_SECTIONS,
  },
  {
    id: 'batik-heritage',
    name: 'Batik Heritage',
    name_ms: 'Warisan Batik',
    description: 'Rich earth tones inspired by Malaysian batik — cultural pride',
    preview_colors: ['#8B4513', '#CD853F', '#FFF8DC', '#3E1F0D'],
    theme_config: {
      primary_color: '#8B4513',
      secondary_color: '#CD853F',
      accent_color: '#F5DEB3',
      bg_color: '#FFF8DC',
      text_color: '#3E1F0D',
      font_display: 'Playfair Display',
      font_body: 'Poppins',
      font_arabic: 'Amiri',
      ornament_style: 'batik',
    },
    default_sections: DEFAULT_SECTIONS,
  },
  {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    name_ms: 'Mimpi Lavender',
    description: 'Soft purple and lilac — dreamy and whimsical',
    preview_colors: ['#7B6B8D', '#B8A9C9', '#F8F5FC', '#2D2438'],
    theme_config: {
      primary_color: '#7B6B8D',
      secondary_color: '#B8A9C9',
      accent_color: '#E8DFF0',
      bg_color: '#F8F5FC',
      text_color: '#2D2438',
      font_display: 'Cormorant Garamond',
      font_body: 'Poppins',
      font_arabic: 'Amiri',
      ornament_style: 'floral',
    },
    default_sections: DEFAULT_SECTIONS,
  },
  {
    id: 'white-minimal',
    name: 'White Minimal',
    name_ms: 'Putih Minimalis',
    description: 'Clean white with black typography — modern minimalist',
    preview_colors: ['#333333', '#999999', '#FFFFFF', '#111111'],
    theme_config: {
      primary_color: '#333333',
      secondary_color: '#999999',
      accent_color: '#F0F0F0',
      bg_color: '#FFFFFF',
      text_color: '#111111',
      font_display: 'Playfair Display',
      font_body: 'Poppins',
      font_arabic: 'Amiri',
      ornament_style: 'minimal',
    },
    default_sections: DEFAULT_SECTIONS,
  },
];

export function getThemeById(id: string): ThemeTemplate | undefined {
  return THEME_TEMPLATES.find((t) => t.id === id);
}

// Section labels in Malay
export const SECTION_LABELS: Record<string, { label: string; icon: string; description: string }> = {
  cover: { label: 'Muka Depan', icon: 'image', description: 'Halaman pembukaan dengan nama & tarikh' },
  islamic_greeting: { label: 'Salam Pembukaan', icon: 'heart', description: 'Assalamualaikum / Bismillah' },
  invitation_text: { label: 'Ayat Jemputan', icon: 'message', description: 'Teks jemputan rasmi' },
  couple: { label: 'Pengantin', icon: 'users', description: 'Nama dan gambar pengantin' },
  event_details: { label: 'Butiran Majlis', icon: 'calendar', description: 'Tarikh, masa dan tempat' },
  countdown: { label: 'Hitung Mundur', icon: 'clock', description: 'Kira detik ke hari majlis' },
  itinerary: { label: 'Tentatif', icon: 'list', description: 'Aturcara majlis' },
  location: { label: 'Lokasi', icon: 'map-pin', description: 'Peta dan navigasi' },
  contact: { label: 'Hubungi', icon: 'phone', description: 'Nombor telefon & WhatsApp' },
  rsvp: { label: 'RSVP', icon: 'check', description: 'Borang pengesahan kehadiran' },
  money_gift: { label: 'Salam Kaut', icon: 'credit-card', description: 'Hadiah wang / DuitNow' },
  gallery: { label: 'Galeri', icon: 'photo', description: 'Gambar-gambar pengantin' },
  guestbook: { label: 'Buku Tamu', icon: 'book', description: 'Ucapan dari tetamu' },
  calendar_save: { label: 'Simpan Tarikh', icon: 'calendar-plus', description: 'Tambah ke kalendar' },
  footer: { label: 'Penutup', icon: 'chevron-down', description: 'Hashtag & kredit' },
  custom_text: { label: 'Teks Khas', icon: 'text-plus', description: 'Tambah teks bebas' },
  custom_image: { label: 'Gambar Khas', icon: 'photo-plus', description: 'Tambah gambar bebas' },
  custom_video: { label: 'Video Khas', icon: 'video-plus', description: 'Tambah video (YouTube/URL)' },
};
